# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_profile_links_contact_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='room_avatars/'),
        ),
    ]
