# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_message_read_and_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, default='text', max_length=20, null=True),
        ),
    ]
