# Generated by Django 4.2.28 on 2026-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_type_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('deactive', 'Offline')], default='deactive', max_length=20),
        ),
    ]
