# Generated by Django 4.2.28 on 2026-03-17 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_room_is_group_channel_message_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSpotterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('architecture', models.CharField(choices=[('ds_cnn', 'DS-CNN'), ('attention_rnn', 'Attention RNN'), ('tc_resnet', 'TC-ResNet'), ('conformer', 'Conformer'), ('multi_head', 'Multi-Head')], max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('model_path', models.CharField(max_length=500)),
                ('tflite_path', models.CharField(blank=True, max_length=500)),
                ('num_parameters', models.IntegerField(default=0)),
                ('num_keywords', models.IntegerField(default=25)),
                ('accuracy', models.FloatField(default=0.0)),
                ('training_epochs', models.IntegerField(default=0)),
                ('training_samples', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trutim_kws_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_dir', models.CharField(max_length=500)),
                ('num_samples', models.IntegerField(default=0)),
                ('num_keywords', models.IntegerField(default=0)),
                ('sample_rate', models.IntegerField(default=16000)),
                ('duration_per_sample_s', models.FloatField(default=1.0)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trutim_training_datasets',
            },
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_commands', models.IntegerField(default=0)),
                ('successful_commands', models.IntegerField(default=0)),
                ('total_audio_duration_s', models.FloatField(default=0.0)),
                ('wake_word_detections', models.IntegerField(default=0)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trutim_voice_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('wake_word', models.CharField(default='trutim', max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('noise_reduction_level', models.CharField(choices=[('off', 'Off'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('use_vad', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trutim_voice_profiles',
            },
        ),
        migrations.CreateModel(
            name='VoiceCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('intent', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('command_result', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('keywords_spotted', models.JSONField(blank=True, default=list)),
                ('wake_word_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_commands', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trutim_voice_command_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
